from collections.abc import AsyncIterator, Awaitable, Callable, Coroutine, Generator, Iterable
from types import TracebackType
from typing import Any, Literal, TypeAlias, TypeVar, overload

_T = TypeVar('_T')
_T1 = TypeVar('_T1')
_T2 = TypeVar('_T2')
_T3 = TypeVar('_T3')
_T4 = TypeVar('_T4')
_T5 = TypeVar('_T5')
_T6 = TypeVar('_T6')

class Future(Awaitable[_T]):
    """
    The one future type: `asyncio.Future`, the answer slot for an external
    call, and the object an `asyncio.Task` settles.
    """
    def __init__(self) -> None: ...
    def __await__(self) -> Generator[Any, None, _T]: ...
    def done(self) -> bool: ...
    def cancelled(self) -> bool: ...
    def result(self) -> _T: ...
    def exception(self) -> BaseException | None: ...
    def cancel(self, msg: Any = None) -> bool: ...
    def set_result(self, result: _T, /) -> None: ...
    def set_exception(self, exception: BaseException, /) -> None: ...
    def add_done_callback(self, callback: Callable[[Future[_T]], object], /) -> None: ...
    def remove_done_callback(self, callback: Callable[[Future[_T]], object], /) -> int: ...

class Task(Future[_T]):
    def __init__(self, coro: Coroutine[Any, Any, _T], /) -> None: ...
    def get_name(self) -> str: ...
    def set_name(self, value: object, /) -> None: ...
    def get_coro(self) -> Coroutine[Any, Any, _T] | None: ...
    def cancelling(self) -> int: ...
    def uncancel(self) -> int: ...

# The gather overloads below were written against this name.
_Future: TypeAlias = Future
_FutureLike: TypeAlias = Future[_T] | Awaitable[_T]

def run(main: Awaitable[_T], *, debug: bool | None = None, loop_factory: Any = None) -> _T: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1], /, *, return_exceptions: Literal[False] = False
) -> _Future[tuple[_T1]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    /,
    *,
    return_exceptions: Literal[False] = False,
) -> _Future[tuple[_T1, _T2]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    /,
    *,
    return_exceptions: Literal[False] = False,
) -> _Future[tuple[_T1, _T2, _T3]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    /,
    *,
    return_exceptions: Literal[False] = False,
) -> _Future[tuple[_T1, _T2, _T3, _T4]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    coro_or_future5: _FutureLike[_T5],
    /,
    *,
    return_exceptions: Literal[False] = False,
) -> _Future[tuple[_T1, _T2, _T3, _T4, _T5]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    coro_or_future5: _FutureLike[_T5],
    coro_or_future6: _FutureLike[_T6],
    /,
    *,
    return_exceptions: Literal[False] = False,
) -> _Future[tuple[_T1, _T2, _T3, _T4, _T5, _T6]]: ...
@overload
def gather(*coros_or_futures: _FutureLike[_T], return_exceptions: Literal[False] = False) -> _Future[list[_T]]: ...
@overload
def gather(coro_or_future1: _FutureLike[_T1], /, *, return_exceptions: bool) -> _Future[tuple[_T1 | BaseException]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1], coro_or_future2: _FutureLike[_T2], /, *, return_exceptions: bool
) -> _Future[tuple[_T1 | BaseException, _T2 | BaseException]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    /,
    *,
    return_exceptions: bool,
) -> _Future[tuple[_T1 | BaseException, _T2 | BaseException, _T3 | BaseException]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    /,
    *,
    return_exceptions: bool,
) -> _Future[tuple[_T1 | BaseException, _T2 | BaseException, _T3 | BaseException, _T4 | BaseException]]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    coro_or_future5: _FutureLike[_T5],
    /,
    *,
    return_exceptions: bool,
) -> _Future[
    tuple[_T1 | BaseException, _T2 | BaseException, _T3 | BaseException, _T4 | BaseException, _T5 | BaseException]
]: ...
@overload
def gather(
    coro_or_future1: _FutureLike[_T1],
    coro_or_future2: _FutureLike[_T2],
    coro_or_future3: _FutureLike[_T3],
    coro_or_future4: _FutureLike[_T4],
    coro_or_future5: _FutureLike[_T5],
    coro_or_future6: _FutureLike[_T6],
    /,
    *,
    return_exceptions: bool,
) -> _Future[
    tuple[
        _T1 | BaseException,
        _T2 | BaseException,
        _T3 | BaseException,
        _T4 | BaseException,
        _T5 | BaseException,
        _T6 | BaseException,
    ]
]: ...
@overload
def gather(*coros_or_futures: _FutureLike[_T], return_exceptions: bool) -> _Future[list[_T | BaseException]]: ...
def sleep(delay: float, result: _T = ...) -> Future[_T]: ...
def ensure_future(coro_or_future: _FutureLike[_T], /) -> Future[_T]: ...
def create_task(coro: Coroutine[Any, Any, _T], /) -> Task[_T]: ...
def wait(
    fs: Iterable[Future[_T]], *, timeout: float | None = None, return_when: str = ...
) -> Future[tuple[set[Future[_T]], set[Future[_T]]]]: ...
def as_completed(fs: Iterable[_FutureLike[_T]], /) -> AsyncIterator[Future[_T]]: ...
def current_task() -> Task[Any] | None: ...
def iscoroutine(obj: object, /) -> bool: ...
def isfuture(obj: object, /) -> bool: ...
def timeout(delay: float | None, /) -> Timeout: ...
def timeout_at(when: float | None, /) -> Timeout: ...

FIRST_COMPLETED: str
FIRST_EXCEPTION: str
ALL_COMPLETED: str

class CancelledError(BaseException): ...
class InvalidStateError(Exception): ...
class QueueEmpty(Exception): ...
class QueueFull(Exception): ...

class Lock:
    def __init__(self) -> None: ...
    def locked(self) -> bool: ...
    def acquire(self) -> Future[bool]: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> bool: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
        /,
    ) -> None: ...

class Event:
    def __init__(self) -> None: ...
    def is_set(self) -> bool: ...
    def set(self) -> None: ...
    def clear(self) -> None: ...
    def wait(self) -> Future[bool]: ...

class Semaphore:
    def __init__(self, value: int = 1, /) -> None: ...
    def locked(self) -> bool: ...
    def acquire(self) -> Future[bool]: ...
    def release(self) -> None: ...
    async def __aenter__(self) -> bool: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
        /,
    ) -> None: ...

class BoundedSemaphore(Semaphore): ...

class Barrier:
    parties: int
    n_waiting: int
    def __init__(self, parties: int, /) -> None: ...
    def wait(self) -> Future[int]: ...

class Queue:
    maxsize: int
    def __init__(self, maxsize: int = 0, /) -> None: ...
    def qsize(self) -> int: ...
    def empty(self) -> bool: ...
    def full(self) -> bool: ...
    def put(self, item: Any, /) -> Future[None]: ...
    def put_nowait(self, item: Any, /) -> None: ...
    def get(self) -> Future[Any]: ...
    def get_nowait(self) -> Any: ...
    def task_done(self) -> None: ...
    def join(self) -> Future[None]: ...

class TaskGroup:
    def __init__(self) -> None: ...
    def create_task(self, coro: Coroutine[Any, Any, _T], /) -> Task[_T]: ...
    async def __aenter__(self) -> TaskGroup: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
        /,
    ) -> None: ...

class Timeout:
    async def __aenter__(self) -> None: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
        /,
    ) -> None: ...
