# Based on python/typeshed's `stdlib/_contextvars.pyi`, narrowed to what Monty
# implements and written as `contextvars` itself: there is no `_contextvars`
# module to re-export from, so the two classes are declared here.
#
# `Context` and `copy_context()` are absent because Monty runs one implicit
# context, and `Token.old_value` / `Token.MISSING` because a token exposes only
# the variable it belongs to. Extend this in lockstep with
# `crates/monty/src/modules/contextvars.rs`; see limitations/contextvars.md.

from types import GenericAlias, TracebackType
from typing import Any, Generic, TypeVar, final, overload

from typing_extensions import Self

_T = TypeVar('_T')
_D = TypeVar('_D')

@final
class ContextVar(Generic[_T]):
    @overload
    def __new__(cls, name: str) -> Self: ...
    @overload
    def __new__(cls, name: str, *, default: _T) -> Self: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @overload
    def get(self) -> _T: ...
    @overload
    def get(self, default: _T, /) -> _T: ...
    @overload
    def get(self, default: _D, /) -> _D | _T: ...
    def set(self, value: _T, /) -> Token[_T]: ...
    def reset(self, token: Token[_T], /) -> None: ...
    def __class_getitem__(cls, item: Any, /) -> GenericAlias: ...

@final
class Token(Generic[_T]):
    @property
    def var(self) -> ContextVar[_T]: ...
    def __class_getitem__(cls, item: Any, /) -> GenericAlias: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None, /
    ) -> None: ...
