//! Implementation of Python's `dataclasses` module.
//!
//! Native, in-sandbox `@dataclass`: the decorator writes a `__dataclass_fields__`
//! mapping of [`DataclassField`]s and a `__dataclass_params__` entry of options
//! into the class namespace, and the dunders are synthesized off the two, with no
//! `exec` and no generated bytecode. This module owns the whole feature; the
//! generic machinery calls in through narrow hooks in `bytecode::vm::call`
//! (construction) and `types::instance` (value dunders).
//!
//! See `limitations/dataclasses.md` for divergences from CPython.

mod field;
mod helpers;
mod options;

use std::fmt::Write;

use smallvec::SmallVec;

use self::options::dataclass_options;
pub(crate) use self::{
    field::{DataclassField, MISSING},
    options::DataclassParams,
};
use crate::{
    args::{ArgValues, FromArgs, KwargsValues},
    builtins::Builtins,
    bytecode::{CallResult, VM},
    defer_drop, defer_drop_mut,
    exception_private::{ExcType, ExcTypeExt, RunError, RunResult, SimpleException},
    hash::HashValue,
    heap::{DropGuard, DropWithContext, HeapData, HeapId, HeapRead, HeapReadOutput},
    intern::{StaticStrings, StringId},
    modules::ModuleFunctions,
    types::{
        Class, CmpOrder, DataclassOptions, Dict, Instance, LazyHeapSet, Module, Opt, PyTrait,
        dataclass::write_dataclass_repr,
        instance::{class_defines, class_dunder, class_name, instance_attr},
        tuple::allocate_tuple,
    },
    value::Value,
};

/// `dataclasses` module functions: each variant is a Python-visible callable.
///
/// [`Configured`](Self::Configured) is what `@dataclass(...)` evaluates to
/// before it is applied. Carrying the options inline keeps that intermediate an
/// immediate `Value`, so the two-call decorator syntax allocates nothing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, strum::Display, serde::Serialize, serde::Deserialize)]
#[strum(serialize_all = "snake_case")]
pub(crate) enum DataclassesFunctions {
    /// The `@dataclass` decorator.
    Dataclass,
    /// The decorator `@dataclass(...)` returns, holding its keyword options.
    #[strum(serialize = "dataclass")]
    Configured(DataclassOptions),
    /// `is_dataclass(obj)`: true for a dataclass class or instance.
    IsDataclass,
    /// `field(...)`: configures one field before its class claims it.
    Field,
    /// `fields(obj)`: the class's `Field` objects, in definition order.
    Fields,
    /// `asdict(obj)`: the instance as a nested dict.
    Asdict,
    /// `astuple(obj)`: the instance as a nested tuple.
    Astuple,
    /// `replace(obj, **changes)`: a new instance with some fields replaced.
    Replace,
}

/// Creates the `dataclasses` module and allocates it on the heap.
pub fn create_module(vm: &mut VM<'_>) -> HeapId {
    let mut module = Module::new(StaticStrings::Dataclasses);
    for (name, func) in [
        (StaticStrings::Dataclass, DataclassesFunctions::Dataclass),
        (StaticStrings::IsDataclass, DataclassesFunctions::IsDataclass),
        (StaticStrings::Field, DataclassesFunctions::Field),
        (StaticStrings::Fields, DataclassesFunctions::Fields),
        (StaticStrings::Asdict, DataclassesFunctions::Asdict),
        (StaticStrings::Astuple, DataclassesFunctions::Astuple),
        (StaticStrings::Replace, DataclassesFunctions::Replace),
    ] {
        module.set_attr(name, Value::ModuleFunction(ModuleFunctions::Dataclasses(func)), vm);
    }
    // An immediate value, so the sentinel needs no allocation and compares by
    // identity wherever it travels.
    module.set_attr(StaticStrings::Missing, MISSING, vm);
    module.set_attr(
        StaticStrings::FrozenInstanceError,
        Value::Builtin(Builtins::ExcType(ExcType::FrozenInstanceError)),
        vm,
    );
    vm.heap.allocate(HeapData::Module(Box::new(module)))
}

/// Dispatches a `dataclasses` module function call.
pub(super) fn call(vm: &mut VM<'_>, func: DataclassesFunctions, args: ArgValues) -> RunResult<Value> {
    match func {
        DataclassesFunctions::Dataclass => dataclass_decorator(vm, args),
        DataclassesFunctions::Configured(options) => {
            let ConfiguredArgs { cls } = ConfiguredArgs::from_args(args, vm)?;
            apply_dataclass(vm, cls, options)
        }
        DataclassesFunctions::IsDataclass => helpers::is_dataclass(vm, args),
        DataclassesFunctions::Field => field::field(vm, args),
        DataclassesFunctions::Fields => helpers::fields(vm, args),
        DataclassesFunctions::Asdict => helpers::asdict(vm, args),
        DataclassesFunctions::Astuple => helpers::astuple(vm, args),
        DataclassesFunctions::Replace => helpers::replace(vm, args),
    }
}

/// The `@dataclass` decorator in both of its forms.
///
/// Applied directly (`@dataclass`, one positional class) it decorates on the
/// spot; called with options (`@dataclass(frozen=True)`, or the bare
/// `@dataclass()`) it hands back the configured decorator, exactly as CPython's
/// `cls=None` signature does.
fn dataclass_decorator(vm: &mut VM<'_>, args: ArgValues) -> RunResult<Value> {
    let (cls, options) = dataclass_options(vm, args)?;
    match cls {
        Some(cls) => apply_dataclass(vm, cls, options),
        None => Ok(Value::ModuleFunction(ModuleFunctions::Dataclasses(
            DataclassesFunctions::Configured(options),
        ))),
    }
}

/// The class a [`DataclassesFunctions::Configured`] decorator is waiting for.
///
/// CPython's `dataclass` closes over a plain `def wrap(cls)`, so the class binds
/// positionally *or* by keyword, and the arity errors name that closure rather
/// than `dataclass` itself. Raw `Value` because a `def` type-checks nothing, and
/// `apply_dataclass` makes the class check the body would.
#[derive(FromArgs)]
#[from_args(name = "dataclass.<locals>.wrap", style = def)]
struct ConfiguredArgs {
    cls: Value,
}

/// Decorates `cls` with `options`: records the fields and the options on the
/// class, so every synthesized dunder can read both back.
///
/// Ownership of the class passes straight through to the return value, so it is
/// only released when something below rejects it, which the guard handles on
/// every path.
fn apply_dataclass(vm: &mut VM<'_>, cls: Value, options: DataclassOptions) -> RunResult<Value> {
    let mut guard = DropGuard::new(cls, vm);
    let (cls, vm) = guard.as_parts();
    // Read once and pass the handle down: everything below then works from a
    // value already known to be a class, and the guard's reference keeps it alive.
    let Value::Ref(class_id) = cls else {
        return Err(non_class_error(cls, vm));
    };
    let class_id = *class_id;
    let HeapReadOutput::Class(mut class) = vm.heap.read(class_id) else {
        return Err(non_class_error(cls, vm));
    };
    let fields = build_dataclass_fields(&class, options, vm)?;
    store_dataclass_metadata(&mut class, class_id, fields, options, vm)?;
    // Last, so the options a class acts on are only ever those of a decoration
    // that ran to completion. Assigning to `__dataclass_params__` afterwards
    // does not reach here, which is what makes that object a report.
    class.set_dataclass_options(options, vm);
    Ok(guard.into_inner())
}

/// `dataclass()` applied to something that is not a class.
fn non_class_error(cls: &Value, vm: &VM<'_>) -> RunError {
    let type_name = cls.py_type_name(vm);
    SimpleException::new_msg(
        ExcType::TypeError,
        format!("dataclass() should be called on a class, not '{type_name}'"),
    )
    .into()
}

/// Builds the `name -> Field` mapping for `class` from its `__annotations__`:
/// the annotated names in definition order, minus `ClassVar` entries, each
/// carrying the default (or the `field()` configuration) the class namespace
/// bound for it.
///
/// Also where a class body Monty cannot yet honour is rejected, so an
/// unimplemented feature raises rather than producing a subtly wrong class
/// (see `limitations/dataclasses.md`). The fields are guarded throughout, so a
/// rejection releases the defaults already captured.
///
/// Check order is CPython's: a per-field default is validated as the field is
/// collected, then the whole-class option conflicts, then the signature the
/// field order would produce, then the hash conflict.
fn build_dataclass_fields<'h>(
    class: &HeapRead<'h, Class>,
    options: DataclassOptions,
    vm: &mut VM<'h>,
) -> RunResult<Value> {
    let fields = collect_annotated_fields(class, options, vm);
    let mut guard = DropGuard::new(fields, vm);
    let (fields, vm) = guard.as_parts();
    validate_defaults(vm, fields)?;
    options.validate_ordering()?;
    validate_field_order(vm, fields)?;
    options.validate_slots()?;
    validate_hash_override(class, options, vm)?;
    let (fields, vm) = guard.into_parts();
    allocate_fields_dict(vm, fields)
}

/// Allocates the dict `__dataclass_fields__` holds, consuming the collected
/// fields. The dict owns every `Field` from its first insertion, so a failure
/// part-way releases them with it.
fn allocate_fields_dict(vm: &mut VM<'_>, fields: Vec<DataclassField>) -> RunResult<Value> {
    let dict_id = vm.heap.allocate(HeapData::Dict(Dict::with_capacity(fields.len())));
    let mut guard = DropGuard::new(Value::Ref(dict_id), vm);
    let vm = guard.ctx();
    for field in fields {
        let name = field.name();
        let field_id = vm.heap.allocate(HeapData::DataclassField(Box::new(field)));
        let HeapReadOutput::Dict(mut dict) = vm.heap.read(dict_id) else {
            unreachable!("the dict was just allocated")
        };
        // Annotation keys are unique, so nothing is ever replaced: released
        // rather than asserted away so a future duplicate cannot leak. A dict
        // rejected by the memory limit releases the field it was handed.
        let replaced = dict.set(Value::InternString(name), Value::Ref(field_id), vm)?;
        replaced.drop_with(vm);
    }
    Ok(guard.into_inner())
}

/// Writes what the decorated class advertises: `__dataclass_fields__`,
/// `__dataclass_params__`, and (unless the body wrote one, or `match_args` is
/// off) `__match_args__`. Takes ownership of `fields`.
///
/// Finally rewrites the class attributes the `field()` specs occupied, as
/// CPython does: a spec with a plain default leaves that default behind, and
/// one without leaves nothing, so `C.x` on a factory-defaulted field raises.
fn store_dataclass_metadata<'h>(
    class: &mut HeapRead<'h, Class>,
    class_id: HeapId,
    fields: Value,
    options: DataclassOptions,
    vm: &mut VM<'h>,
) -> RunResult<()> {
    // Re-decorating replaces the previous mapping, which nothing else owns once
    // it is out of the namespace.
    let replaced = class.set_attr(StaticStrings::DataclassFields.into(), fields, vm)?;
    replaced.drop_with(vm);
    let params = vm
        .heap
        .allocate(HeapData::DataclassParams(DataclassParams::new(options)));
    let replaced = class.set_attr(StaticStrings::DataclassParams.into(), Value::Ref(params), vm)?;
    replaced.drop_with(vm);
    if options.get(Opt::MatchArgs) && !body_defines(class, "__match_args__", vm) {
        let match_args = match_args_tuple(class_id, vm);
        let replaced = class.set_attr(StaticStrings::DunderMatchArgs.into(), match_args, vm)?;
        replaced.drop_with(vm);
    }
    rebind_spec_attributes(class, class_id, vm)
}

/// `__match_args__`: the fields a positional pattern binds, which are the
/// init-able ones the constructor takes positionally.
fn match_args_tuple(class_id: HeapId, vm: &mut VM<'_>) -> Value {
    let names: SmallVec<[Value; 2]> = field_specs(class_id, vm)
        .iter()
        .filter(|spec| spec.init && !spec.kw_only)
        .map(|spec| Value::InternString(spec.name))
        .collect();
    allocate_tuple(names, vm.heap)
}

/// Replaces each class attribute still holding a `field()` spec with that
/// field's plain default, or unbinds it when there is none.
fn rebind_spec_attributes<'h>(class: &mut HeapRead<'h, Class>, class_id: HeapId, vm: &mut VM<'h>) -> RunResult<()> {
    for spec in field_specs(class_id, vm) {
        let name = Value::InternString(spec.name);
        let is_spec = matches!(
            class.get(vm.heap).namespace().get_by_str(vm.interns.get_str(spec.name), vm.heap, vm.interns),
            Some(Value::Ref(id)) if matches!(vm.heap.get(*id), HeapData::DataclassField(_))
        );
        if !is_spec {
            continue;
        }
        if let Some(default) = captured_default(vm, class_id, spec.index) {
            let replaced = class.set_attr(name, default, vm)?;
            replaced.drop_with(vm);
        } else {
            let removed = class.del_attr(&name, vm)?;
            removed.drop_with(vm);
        }
    }
    Ok(())
}

/// Whether the class body itself binds `name`, which the decorator must not
/// overwrite (CPython leaves an explicitly written member alone).
fn body_defines<'h>(class: &HeapRead<'h, Class>, name: &str, vm: &VM<'h>) -> bool {
    class
        .get(vm.heap)
        .namespace()
        .get_by_str(name, vm.heap, vm.interns)
        .is_some()
}

/// Collects the dataclass fields from `__annotations__`, in definition order,
/// dropping `ClassVar` entries.
///
/// A class-body value that is a `field()` spec configures its field; anything
/// else is the plain default, captured now (as CPython bakes it into the
/// generated `__init__`) so rebinding the class attribute later cannot change it.
///
/// Each field owns its annotation and captured values from here on, so a caller
/// that discards the result must release them (`drop_with`).
fn collect_annotated_fields<'h>(
    class: &HeapRead<'h, Class>,
    options: DataclassOptions,
    vm: &VM<'h>,
) -> Vec<DataclassField> {
    let namespace = class.get(vm.heap).namespace();
    let ann_id = match namespace.get_by_str("__annotations__", vm.heap, vm.interns) {
        Some(Value::Ref(id)) => *id,
        _ => return Vec::new(),
    };
    let HeapData::Dict(annotations) = vm.heap.get(ann_id) else {
        return Vec::new();
    };
    let class_kw_only = options.get(Opt::KwOnly);
    let mut fields = Vec::new();
    for (key, annotation) in annotations {
        // Annotation keys are always interned field-name strings.
        let Value::InternString(name_id) = key else { continue };
        // `ClassVar[...]` entries are class variables, not dataclass fields.
        if is_classvar(&annotation_text(annotation, vm)) {
            continue;
        }
        let bound = namespace.get_by_str(vm.interns.get_str(*name_id), vm.heap, vm.interns);
        let annotation = annotation.clone_with_heap(vm.heap);
        // The class body keeps owning any `field()` spec, so the field is built
        // from a clone of it; anything else is the plain default.
        fields.push(if let Some(spec) = spec_of(bound, vm) {
            let mut claimed = spec.clone_with_heap(vm.heap);
            claimed.claim(*name_id, annotation, class_kw_only);
            claimed
        } else {
            let mut plain = DataclassField::new(*name_id, annotation, bound.map(|v| v.clone_with_heap(vm.heap)));
            plain.settle_kw_only(class_kw_only);
            plain
        });
    }
    fields
}

/// The `field()` spec a class-body value holds, or `None` for a plain default.
fn spec_of<'v>(bound: Option<&Value>, vm: &'v VM<'_>) -> Option<&'v DataclassField> {
    match bound {
        Some(Value::Ref(id)) => match vm.heap.get(*id) {
            HeapData::DataclassField(field) => Some(field),
            _ => None,
        },
        _ => None,
    }
}

/// A stringized annotation as text, or `""` for the non-string annotations
/// Monty never produces (it always stores annotations as source text).
fn annotation_text(annotation: &Value, vm: &VM<'_>) -> String {
    annotation
        .as_either_str(vm.heap)
        .map(|s| s.as_str(vm.interns).to_owned())
        .unwrap_or_default()
}

/// Rejects the per-field defaults CPython rejects, in its checking order.
fn validate_defaults(vm: &mut VM<'_>, fields: &[DataclassField]) -> RunResult<()> {
    for field in fields {
        let name = vm.interns.get_str(field.name()).to_owned();
        let annotation = annotation_text(field.annotation(), vm);
        if is_initvar(&annotation) {
            return Err(ExcType::not_implemented(format!(
                "dataclass() does not yet support InitVar (field {name}), which would become an ordinary field"
            ))
            .into());
        }
        if annotation_head(&annotation, "KW_ONLY") {
            return Err(ExcType::not_implemented(format!(
                "dataclass() does not yet support the KW_ONLY marker (field {name}), \
                 which would become an ordinary field instead of making the rest keyword-only"
            ))
            .into());
        }
        if let Some(default) = field.default() {
            // CPython's rule is hashability, not a list/dict/set type check, so
            // a class with `__hash__ = None` is rejected the same way. Borrowed,
            // not consumed: `build_dataclass_fields` releases it on rejection.
            if default.py_hash(vm)?.is_none() {
                let ty = default.py_type_name(vm);
                return Err(ExcType::value_error(format!(
                    "mutable default <class '{ty}'> for field {name} is not allowed: use default_factory"
                )));
            }
        }
    }
    Ok(())
}

/// Rejects a field order that would produce an invalid `__init__` signature.
///
/// CPython rejects the class outright rather than failing at construction, and
/// only weighs the fields `__init__` actually takes positionally.
fn validate_field_order(vm: &VM<'_>, fields: &[DataclassField]) -> RunResult<()> {
    let mut last_default: Option<StringId> = None;
    for field in fields.iter().filter(|f| f.init() && !f.kw_only()) {
        if field.has_default() {
            last_default = Some(field.name());
        } else if let Some(prev) = last_default {
            let (prev, name) = (vm.interns.get_str(prev), vm.interns.get_str(field.name()));
            return Err(ExcType::type_error(format!(
                "non-default argument '{name}' follows default argument '{prev}'"
            )));
        }
    }
    Ok(())
}

/// `unsafe_hash=True` refuses to replace a `__hash__` the class body wrote.
fn validate_hash_override<'h>(class: &HeapRead<'h, Class>, options: DataclassOptions, vm: &VM<'h>) -> RunResult<()> {
    if options.get(Opt::UnsafeHash) && body_defines(class, "__hash__", vm) {
        let name = class.get(vm.heap).name().as_str(vm.interns);
        return Err(ExcType::type_error(format!(
            "Cannot overwrite attribute __hash__ in class {name}"
        )));
    }
    Ok(())
}

/// Whether a stringized annotation denotes `typing.ClassVar`, so the field is
/// excluded.
///
/// Detection is textual where CPython resolves the annotation through the
/// defining module, so neither the import nor a dotted spelling's module is
/// checked; both divergences are in `limitations/dataclasses.md`.
fn is_classvar(annotation: &str) -> bool {
    annotation_head(annotation, "ClassVar")
}

/// Whether a stringized annotation denotes `dataclasses.InitVar`. Matched the
/// same way as [`is_classvar`], and with the same textual-only caveats.
fn is_initvar(annotation: &str) -> bool {
    annotation_head(annotation, "InitVar")
}

/// Whether a stringized annotation names `name`, bare, subscripted, or
/// dotted (`typing.ClassVar[int]`), ignoring surrounding whitespace and quotes.
///
/// Quotes must be stripped because a quoted annotation (`x: "ClassVar[int]"`)
/// is stringized with its quotes intact. The subscript is split off before the
/// qualifier check so a dotted type argument (`ClassVar[a.b]`) still matches.
fn annotation_head(annotation: &str, name: &str) -> bool {
    let s = annotation.trim().trim_matches(|c| c == '\'' || c == '"').trim();
    let head = s.split_once('[').map_or(s, |(head, _)| head).trim_end();
    head.rsplit('.').next() == Some(name)
}

/// The `__dataclass_fields__` dict a class namespace holds, or `None` when the
/// class is not a dataclass.
///
/// Every reader goes through the namespace, so a class whose
/// `__dataclass_fields__` sandboxed code overwrote simply stops being a
/// dataclass rather than reading metadata the class no longer advertises.
fn fields_dict_id(namespace: &Dict, vm: &VM<'_>) -> Option<HeapId> {
    match namespace.get_by_str(StaticStrings::DataclassFields.into(), vm.heap, vm.interns) {
        Some(Value::Ref(id)) if matches!(vm.heap.get(*id), HeapData::Dict(_)) => Some(*id),
        _ => None,
    }
}

/// [`fields_dict_id`] for the callers holding only a class `HeapId`: the
/// generic `Instance` code, which reaches a class through its instance.
fn class_fields_dict_id(class_id: HeapId, vm: &VM<'_>) -> Option<HeapId> {
    match vm.heap.get(class_id) {
        HeapData::Class(class) => fields_dict_id(class.namespace(), vm),
        _ => None,
    }
}

/// Whether `class_id` names a dataclass.
pub(crate) fn is_dataclass_class(class_id: HeapId, vm: &VM<'_>) -> bool {
    class_fields_dict_id(class_id, vm).is_some()
}

/// Whether constructing `class_id` binds its fields natively, which is what a
/// dataclass with no user `__init__` and `init=True` does.
pub(crate) fn has_synthesized_init(class_id: HeapId, vm: &VM<'_>) -> bool {
    is_dataclass_class(class_id, vm) && class_options(class_id, vm).get(Opt::Init)
}

/// The options `class_id` was decorated with, or the defaults when the class is
/// not a dataclass (or sandboxed code replaced `__dataclass_params__`).
fn class_options(class_id: HeapId, vm: &VM<'_>) -> DataclassOptions {
    match vm.heap.get(class_id) {
        HeapData::Class(class) => class.dataclass_options(),
        _ => DataclassOptions::default(),
    }
}

/// One field's binding-relevant shape, owned so the heap borrow is released.
#[derive(Debug, Clone, Copy)]
#[expect(
    clippy::struct_excessive_bools,
    reason = "a snapshot of CPython's per-field flags, one field each"
)]
struct FieldSpec {
    name: StringId,
    /// Position in `__dataclass_fields__`, for reading the field back.
    index: usize,
    init: bool,
    kw_only: bool,
    has_default: bool,
    compare: bool,
    repr: bool,
    hashed: bool,
}

/// Every field of `class_id`, in definition order; empty for a plain class.
fn field_specs(class_id: HeapId, vm: &VM<'_>) -> Vec<FieldSpec> {
    let Some(fields_id) = class_fields_dict_id(class_id, vm) else {
        return Vec::new();
    };
    let HeapData::Dict(fields) = vm.heap.get(fields_id) else {
        return Vec::new();
    };
    fields
        .iter()
        .enumerate()
        .filter_map(|(index, (_, value))| match value {
            Value::Ref(id) => match vm.heap.get(*id) {
                HeapData::DataclassField(field) => Some(FieldSpec {
                    name: field.name(),
                    index,
                    init: field.init(),
                    kw_only: field.kw_only(),
                    has_default: field.has_default(),
                    compare: field.compare(),
                    repr: field.repr(),
                    hashed: field.hashed(),
                }),
                _ => None,
            },
            _ => None,
        })
        .collect()
}

/// Constructs a dataclass instance by binding `args` to the recorded fields,
/// taking ownership of the freshly allocated `instance`.
///
/// No bytecode is generated: arguments bind natively as CPython's synthesized
/// `__init__(self, f1, f2=default, ...)` would, filling unbound fields from the
/// defaults captured at decoration time. Drops the instance on error.
pub(crate) fn dataclass_init<'h>(
    vm: &mut VM<'h>,
    class: &HeapRead<'h, Class>,
    class_id: HeapId,
    instance: Value,
    args: ArgValues,
) -> Result<CallResult, RunError> {
    // Owned field metadata, releasing the heap borrow.
    let fields = field_specs(class_id, vm);

    // The instance is owned throughout: the guard releases it if binding,
    // storing or `__post_init__` fails, and hands it back on success.
    let mut guard = DropGuard::new(instance, vm);
    {
        let (instance, vm) = guard.as_parts();
        let &Value::Ref(instance_id) = instance else {
            unreachable!("the caller just allocated the instance")
        };
        // Read once for the whole binding. The handle is scoped tighter than
        // the guard so it is released first: a guard that frees the instance
        // must not find a live reader.
        let HeapReadOutput::Instance(mut instance) = vm.heap.read(instance_id) else {
            unreachable!("the caller just allocated the instance")
        };
        let values = bind_dataclass_fields(vm, class, class_id, &fields, args)?;
        store_bound_fields(&mut instance, &fields, values, vm)?;
    }
    {
        let (instance, vm) = guard.as_parts();
        let &Value::Ref(instance_id) = instance else {
            unreachable!("the caller just allocated the instance")
        };
        run_post_init(instance_id, vm)?;
    }
    Ok(CallResult::Value(guard.into_inner()))
}

/// Calls the class's `__post_init__` hook, if it defines one.
///
/// Run to completion here rather than as a pushed frame: CPython's generated
/// `__init__` calls it as a statement and ignores what it returns, which the
/// frame path cannot express (it enforces the `None` return `__init__` itself
/// must make). The cost is that the hook cannot suspend on an external or OS
/// call, the same bound every synchronously-dispatched dunder carries.
fn run_post_init(instance_id: HeapId, vm: &mut VM<'_>) -> RunResult<()> {
    let Some(hook) = instance_attr(instance_id, "__post_init__", vm)? else {
        return Ok(());
    };
    defer_drop!(hook, vm);
    let result = vm.evaluate_function("__post_init__", hook, ArgValues::Empty)?;
    result.drop_with(vm);
    Ok(())
}

/// Stores each bound value on the instance `__dict__`, consuming `values`.
///
/// One slot per field, in field order; an empty slot is a field `__init__`
/// neither took nor could fill, which stays unset exactly as in CPython. A set
/// failure (a resource limit) leaves the untouched tail to the guard; the
/// caller owns the instance.
fn store_bound_fields<'h>(
    instance: &mut HeapRead<'h, Instance>,
    fields: &[FieldSpec],
    values: Vec<Option<Value>>,
    vm: &mut VM<'h>,
) -> Result<(), RunError> {
    defer_drop_mut!(values, vm);
    for i in 0..values.len() {
        let Some(value) = values[i].take() else {
            continue;
        };
        // Unchecked: a `frozen=True` instance refuses its own `set_attr`, as
        // CPython's generated `__init__` goes through `object.__setattr__`.
        let replaced = instance.set_attr_unchecked(Value::InternString(fields[i].name), value, vm)?;
        replaced.drop_with(vm);
    }
    Ok(())
}

/// Binds `args` to the fields the synthesized `__init__` takes, and pairs every
/// field the constructor can fill with its value, in field order.
///
/// Bound arguments are guarded, so an error on any path releases them and the
/// unbound ones alike. The instance is untouched; the caller owns it.
///
/// Every key is a string here: `**` unpacking is the only way a non-string one
/// could arrive, and `DictMerge` raises `keywords must be strings` while
/// building the call's kwargs, before any binder runs, as CPython does.
fn bind_dataclass_fields<'h>(
    vm: &mut VM<'h>,
    class: &HeapRead<'h, Class>,
    class_id: HeapId,
    fields: &[FieldSpec],
    args: ArgValues,
) -> Result<Vec<Option<Value>>, RunError> {
    let init_name = format!("{}.__init__", class.get(vm.heap).name().as_str(vm.interns));
    let (pos_iter, kwargs) = args.into_parts();
    // The fields `__init__` takes positionally, in order; the rest are filled
    // by keyword or from their default.
    let positional: Vec<usize> = (0..fields.len())
        .filter(|&i| fields[i].init && !fields[i].kw_only)
        .collect();

    // Every bound argument lands in `values`, guarded so each error below is a
    // plain `?`: nothing else holds an owned reference across them.
    let values: Vec<Option<Value>> = (0..fields.len()).map(|_| None).collect();
    let mut guard = DropGuard::new(values, vm);
    let (values, vm) = guard.as_parts_mut();

    // Positionals fill the leftmost slots; one beyond the last is dropped here
    // and only counted, since CPython binds keywords first: `P(1, 2, 3, y=4)`
    // is "multiple values for argument 'y'", not an arity error.
    let mut n_pos = 0;
    for (slot, value) in pos_iter.enumerate() {
        n_pos += 1;
        match positional.get(slot) {
            Some(&index) => values[index] = Some(value),
            None => value.drop_with(vm),
        }
    }

    bind_keyword_args(values, fields, kwargs, &init_name, vm)?;

    // Too many positionals (CPython counts `self`, so +1 each side), reported
    // only once keyword binding has had its say.
    if n_pos > positional.len() {
        let required = positional.iter().filter(|&&i| !fields[i].has_default).count();
        return Err(ExcType::type_error_too_many_positional_range(
            &init_name,
            1 + required,
            1 + positional.len(),
            1 + n_pos,
            0,
        ));
    }

    // Unbound fields take the default captured at decoration time, or are built
    // by their factory; a field with neither is missing from the call.
    let mut missing_positional: Vec<String> = Vec::new();
    let mut missing_kw_only: Vec<String> = Vec::new();
    for (index, spec) in fields.iter().enumerate() {
        if values[index].is_some() {
            continue;
        }
        match captured_default(vm, class_id, index) {
            Some(default) => values[index] = Some(default),
            None => match factory_default(vm, class_id, index)? {
                Some(built) => values[index] = Some(built),
                // A field `__init__` does not take and cannot fill is simply
                // never set, so reading it raises, exactly as in CPython.
                None if !spec.init => {}
                None if spec.kw_only => missing_kw_only.push(vm.interns.get_str(spec.name).to_owned()),
                None => missing_positional.push(vm.interns.get_str(spec.name).to_owned()),
            },
        }
    }
    if !missing_positional.is_empty() {
        let refs: Vec<&str> = missing_positional.iter().map(String::as_str).collect();
        return Err(ExcType::type_error_missing_positional_with_names(&init_name, &refs));
    }
    if !missing_kw_only.is_empty() {
        let refs: Vec<&str> = missing_kw_only.iter().map(String::as_str).collect();
        return Err(ExcType::type_error_missing_kwonly_with_names(&init_name, &refs));
    }

    Ok(guard.into_inner())
}

/// Fills the named slots of `values` from the keyword arguments.
///
/// The iterator is guarded, so an error mid-mapping raises on the spot and the
/// pairs it never reached are still released. Keys are known to be strings: the
/// caller rejects a non-string one before any binding happens.
fn bind_keyword_args(
    values: &mut [Option<Value>],
    fields: &[FieldSpec],
    kwargs: KwargsValues,
    init_name: &str,
    vm: &mut VM<'_>,
) -> RunResult<()> {
    let kwargs = kwargs.into_iter();
    defer_drop_mut!(kwargs, vm);
    for (key, value) in kwargs.by_ref() {
        defer_drop!(key, vm);
        let name = key
            .as_either_str(vm.heap)
            .expect("DictMerge rejects non-string keys before the call")
            .as_str(vm.interns)
            .to_owned();
        // Resolved before the value is guarded, which borrows the VM. A field
        // `__init__` does not take is not a parameter, so naming it is the same
        // error as naming something that is not a field at all.
        let slot = fields
            .iter()
            .position(|spec| spec.init && vm.interns.get_str(spec.name) == name);
        let value = DropGuard::new(value, vm);
        match slot {
            Some(index) if values[index].is_none() => values[index] = Some(value.into_inner()),
            Some(_) => return Err(ExcType::type_error_duplicate_arg(init_name, &name)),
            None => return Err(ExcType::type_error_unexpected_keyword(init_name, &name)),
        }
    }
    Ok(())
}

/// A fresh reference to the default `@dataclass` captured for field `index`, or
/// `None` for a field with none (a required one, or one built by a factory).
fn captured_default(vm: &VM<'_>, class_id: HeapId, index: usize) -> Option<Value> {
    with_field(vm, class_id, index, |field, vm| {
        field.default().map(|v| v.clone_with_heap(vm.heap))
    })?
}

/// Runs field `index`'s `default_factory`, or `None` when it has none.
///
/// Run to completion (as CPython's generated `__init__` calls it), so a factory
/// that suspends on an external or OS call raises rather than returning a value
/// the instance would never have.
fn factory_default(vm: &mut VM<'_>, class_id: HeapId, index: usize) -> RunResult<Option<Value>> {
    let Some(Some(factory)) = with_field(vm, class_id, index, |field, vm| {
        field.default_factory().map(|v| v.clone_with_heap(vm.heap))
    }) else {
        return Ok(None);
    };
    defer_drop!(factory, vm);
    vm.evaluate_function("dataclass field default_factory", factory, ArgValues::Empty)
        .map(Some)
}

/// Reads field `index` of `class_id`'s `__dataclass_fields__` through `f`, or
/// `None` when the class no longer advertises one there.
fn with_field<T>(
    vm: &VM<'_>,
    class_id: HeapId,
    index: usize,
    f: impl FnOnce(&DataclassField, &VM<'_>) -> T,
) -> Option<T> {
    let fields_id = class_fields_dict_id(class_id, vm)?;
    let HeapData::Dict(fields) = vm.heap.get(fields_id) else {
        return None;
    };
    match fields.value_at(index) {
        Some(Value::Ref(id)) => match vm.heap.get(*id) {
            HeapData::DataclassField(field) => Some(f(field, vm)),
            _ => None,
        },
        _ => None,
    }
}

/// Field-wise `__eq__`: equal only to the *same* dataclass with equal compared
/// fields. Any other operand is `NotImplemented` (`Ok(None)`), leaving the
/// caller on identity.
///
/// Mirrors CPython 3.14's generated `self.a == other.a and self.b == other.b`:
/// left to right, stopping at the first unequal pair, each compared with the
/// `==` *operator* rather than container equality. A class decorated `eq=False`
/// has no such method, so it too reports `NotImplemented`.
pub(crate) fn dataclass_eq(
    self_id: HeapId,
    class_id: HeapId,
    other: &Value,
    vm: &mut VM<'_>,
) -> RunResult<Option<bool>> {
    if !class_options(class_id, vm).get(Opt::Eq) {
        return Ok(None);
    }
    // Only the same dataclass type can be equal; otherwise NotImplemented.
    let &Value::Ref(other_id) = other else {
        return Ok(None);
    };
    if !matches!(vm.heap.get(other_id), HeapData::Instance(inst) if inst.class() == class_id) {
        return Ok(None);
    }
    // Charge a recursion level: two distinct cyclic dataclasses (`a.x = a;
    // b.x = b; a == b`) re-enter here per level and would otherwise overflow
    // the host stack.
    let mut guard = vm.recursion_guard()?;
    let vm = &mut *guard;
    for name in compared_names(class_id, vm) {
        let field_name = vm.interns.get_str(name).to_owned();
        // Both reads are guarded so a failing comparison below (or an early
        // return) cannot strand either value.
        let a = instance_attr(self_id, &field_name, vm)?;
        defer_drop!(a, vm);
        let b = instance_attr(other_id, &field_name, vm)?;
        defer_drop!(b, vm);
        match (a, b) {
            (Some(a), Some(b)) if !a.py_eq_operator(b, vm)? => return Ok(Some(false)),
            (Some(_), Some(_)) => {}
            // The generated `__eq__` reads each field as an attribute, so one
            // that resolves nowhere raises rather than comparing unequal.
            _ => {
                let class_name = class_name(class_id, vm.heap, vm.interns).into_owned();
                return Err(ExcType::attribute_error(&class_name, &field_name));
            }
        }
    }
    Ok(Some(true))
}

/// The fields the generated `__eq__` and ordering methods look at.
fn compared_names(class_id: HeapId, vm: &VM<'_>) -> Vec<StringId> {
    field_specs(class_id, vm)
        .iter()
        .filter(|spec| spec.compare)
        .map(|spec| spec.name)
        .collect()
}

/// The ordering `@dataclass(order=True)` synthesizes.
///
/// CPython's generated methods compare the tuple of compared fields, so this
/// builds both tuples and defers to tuple ordering. A class without ordering,
/// or an operand of a different class, is [`CmpOrder::Incomparable`]: CPython's
/// methods return `NotImplemented` there, which the operators turn into the
/// same unorderable-types `TypeError`, and which leaves `sorted()` reporting
/// it exactly as it reports two plain instances.
pub(crate) fn dataclass_cmp(self_id: HeapId, other_id: HeapId, vm: &mut VM<'_>) -> RunResult<CmpOrder> {
    let HeapData::Instance(instance) = vm.heap.get(self_id) else {
        return Ok(CmpOrder::Incomparable);
    };
    let class_id = instance.class();
    if !class_options(class_id, vm).get(Opt::Order) {
        return Ok(CmpOrder::Incomparable);
    }
    if !matches!(vm.heap.get(other_id), HeapData::Instance(inst) if inst.class() == class_id) {
        return Ok(CmpOrder::Incomparable);
    }
    let names = compared_names(class_id, vm);
    let mine = compared_tuple(self_id, class_id, &names, vm)?;
    defer_drop!(mine, vm);
    let theirs = compared_tuple(other_id, class_id, &names, vm)?;
    defer_drop!(theirs, vm);
    mine.py_cmp(theirs, vm)
}

/// The tuple of `names` read off `self_id`, as the generated methods build it.
fn compared_tuple(self_id: HeapId, class_id: HeapId, names: &[StringId], vm: &mut VM<'_>) -> RunResult<Value> {
    let items: SmallVec<[Value; 2]> = SmallVec::with_capacity(names.len());
    let mut guard = DropGuard::new(items, vm);
    let (items, vm) = guard.as_parts_mut();
    for &name in names {
        let field_name = vm.interns.get_str(name).to_owned();
        let Some(value) = instance_attr(self_id, &field_name, vm)? else {
            let owner = class_name(class_id, vm.heap, vm.interns).into_owned();
            return Err(ExcType::attribute_error(&owner, &field_name));
        };
        items.push(value);
    }
    let (items, vm) = guard.into_parts();
    Ok(allocate_tuple(items, vm.heap))
}

/// The `__hash__` a `@dataclass` decoration generates, where it generates one.
///
/// The cells of CPython's `_hash_action` table that write a `__hash__`; every
/// other cell leaves the class to its own body, which [`hash_action`] reports as
/// `None`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DataclassHash {
    /// CPython's `_hash_add`: hash by the field values, as a tuple of them does.
    FieldWise,
    /// CPython's `_hash_set_none`: value equality without immutability.
    Unhashable,
}

/// Which [`DataclassHash`] `class_id`'s decoration generated, or `None` when
/// CPython would leave the class's own `__hash__` standing — including for a
/// plain class, which is most callers' path.
pub(crate) fn hash_action(class_id: HeapId, vm: &VM<'_>) -> Option<DataclassHash> {
    if !is_dataclass_class(class_id, vm) {
        return None;
    }
    // CPython's `has_explicit_hash`: a `__hash__ = None` beside a body `__eq__`
    // is the opt-out `type` inserted, not one the author wrote, so a generated
    // hash overwrites it. Alone, it is deliberate and survives.
    let explicit_hash = class_dunder(class_id, "__hash__", vm)
        .is_some_and(|hash| !(matches!(hash, Value::None) && class_defines(class_id, "__eq__", vm)));
    if explicit_hash {
        // Every remaining cell of the table leaves that `__hash__` standing;
        // `unsafe_hash=True` against one is refused at decoration instead.
        return None;
    }
    let options = class_options(class_id, vm);
    if options.get(Opt::UnsafeHash) {
        return Some(DataclassHash::FieldWise);
    }
    match (options.get(Opt::Eq), options.get(Opt::Frozen)) {
        (true, true) => Some(DataclassHash::FieldWise),
        (true, false) => Some(DataclassHash::Unhashable),
        (false, _) => None,
    }
}

/// The generated `__hash__`: `hash()` of the tuple of hashed fields, which is
/// what CPython's `hash((self.a, self.b))` computes.
pub(crate) fn dataclass_hash(self_id: HeapId, class_id: HeapId, vm: &mut VM<'_>) -> RunResult<Option<HashValue>> {
    let names: Vec<StringId> = field_specs(class_id, vm)
        .iter()
        .filter(|spec| spec.hashed)
        .map(|spec| spec.name)
        .collect();
    let tuple = compared_tuple(self_id, class_id, &names, vm)?;
    defer_drop!(tuple, vm);
    tuple.py_hash(vm)
}

/// The error assigning `name` raises on an instance of `class_id`, or `None`
/// when the write may proceed.
///
/// Every instance assignment passes through here, so the plain-class case is
/// settled before the name is resolved to a string. A name that is not a string
/// cannot be a declared field, so only `frozen` can refuse it.
pub(crate) fn set_attr_error(class_id: HeapId, name: &Value, vm: &VM<'_>) -> Option<RunError> {
    if !is_dataclass_class(class_id, vm) {
        return None;
    }
    let attr = match name.as_either_str(vm.heap) {
        Some(attr) => attr.as_str(vm.interns).to_owned(),
        None => String::new(),
    };
    check_set_attr(class_id, &attr, vm).err()
}

/// Enforces what a decorated class allows to be assigned on an instance.
///
/// `frozen=True` refuses every assignment, `slots=True` refuses names the class
/// never declared (Monty has no `__slots__`, so the restriction is enforced
/// here rather than by the object layout).
pub(crate) fn check_set_attr(class_id: HeapId, attr: &str, vm: &VM<'_>) -> RunResult<()> {
    if !is_dataclass_class(class_id, vm) {
        return Ok(());
    }
    let options = class_options(class_id, vm);
    if options.get(Opt::Frozen) {
        return Err(
            SimpleException::new_msg(ExcType::FrozenInstanceError, format!("cannot assign to field '{attr}'")).into(),
        );
    }
    let declared = field_specs(class_id, vm)
        .iter()
        .any(|spec| vm.interns.get_str(spec.name) == attr);
    if options.get(Opt::Slots) && !declared {
        let name = class_name(class_id, vm.heap, vm.interns);
        return Err(SimpleException::new_msg(
            ExcType::AttributeError,
            format!("'{name}' object has no attribute '{attr}' and no __dict__ for setting new attributes"),
        )
        .into());
    }
    Ok(())
}

/// Synthesized `__repr__`: `ClassName(f1=v1, ...)`, or `Ok(false)` when there
/// is none (a plain class, or one that opted out with `repr=False`) and the
/// caller should fall back to the default object repr.
///
/// Formatting is shared with the host-supplied `Dataclass` via
/// [`write_dataclass_repr`] so the two cannot drift.
pub(crate) fn dataclass_repr_fmt(
    self_id: HeapId,
    class_id: HeapId,
    f: &mut impl Write,
    vm: &mut VM<'_>,
    heap_ids: &mut LazyHeapSet,
) -> RunResult<bool> {
    if !is_dataclass_class(class_id, vm) || !class_options(class_id, vm).get(Opt::Repr) {
        return Ok(false);
    }
    let field_names: Vec<StringId> = field_specs(class_id, vm)
        .iter()
        .filter(|spec| spec.repr)
        .map(|spec| spec.name)
        .collect();
    let name = class_name(class_id, vm.heap, vm.interns).to_string();
    // Each field is read as an attribute at the point it is written, so a field
    // whose `__repr__` mutates a later one is observed, exactly as CPython's
    // generated f-string does. A field that resolves nowhere raises.
    write_dataclass_repr(f, &name, field_names.len(), vm, heap_ids, |i, vm| {
        let field_name = vm.interns.get_str(field_names[i]).to_owned();
        match instance_attr(self_id, &field_name, vm)? {
            Some(value) => Ok((field_name, Some(value))),
            None => Err(ExcType::attribute_error(&name, &field_name)),
        }
    })?;
    Ok(true)
}
